### ISSUE TITLE
Links for the docs and tailwindcss example are broken

### ISSUE THREAD

**Issue by vivz753** [RyanClementsHax/storybook-addon-next#51]
### Describe the bug

Clicking links for all the examples lead to a page `Not Found`, and all of the links under Table of Contents and Supported features do not work, as do some in the contents of the article. Seems like all of the hashed id's are not set for the links to go to that element of the page.

I was able to find the repo for tailwindcss example based on the URL params though, but should be fixed to prevent any confusion

### Your minimal, reproducible example

https://storybook.js.org/addons/storybook-addon-next

### Steps to reproduce

1. Scroll down and click any of the links under Table of Contents, Supported Features, or Examples
2. The page will say `Not Found`

### Expected behavior

Expected to see a working github page for the Example links, and expected the other links to bring me to other parts of the page

### How often does this bug happen?

Every time

### Platform

macOS
Firefox 97.0.1 (64 bit)

### storybook-addon-next version

1.6.1

**Comment by RyanClementsHax** [comment]
Thanks for opening an issue! I'm sorry the docs didn't work for you.

The doc link you provided was actually from storybook's addon catalog which, if I'm correct, scrapes npm for storybook addons. Thus its not the official doc page. The official doc page is the [readme on github](https://github.com/RyanClementsHax/storybook-addon-next#storybook-addon-next-).

The storybook addon catalog pages don't render relative links well unfortunately and there isn't anything in my power to change that especially since both [github](https://github.com/RyanClementsHax/storybook-addon-next) and [npm](https://www.npmjs.com/package/storybook-addon-next) render relative links just fine.

At the very least I could change the links to the example repos to be absolute urls so that they can work on storybook's catalog.

If you know of a way to get relative links working on the catalog page feel free to let me know :)
