### ISSUE TITLE
CSS styles are missing in the result bundle

### ISSUE THREAD

**Issue by PavelZhuravlev** [RyanClementsHax/storybook-addon-next#90]
### Describe the bug

Styles, that I import in `preview.js` are ignored in the result bundle without any issue in the console. Storybook stories are unstyled.
To reproduce the issue, try to run storybook in both development/production mode from your example in the repo
https://github.com/RyanClementsHax/storybook-addon-next/tree/main/examples/with-tailwindcss

I'm facing same issue in real project also.

### Your minimal, reproducible example

https://github.com/RyanClementsHax/storybook-addon-next/tree/main/examples/with-tailwindcss

### Steps to reproduce

To reproduce the issue, try to run storybook in both development/production mode from your example in the repo
https://github.com/RyanClementsHax/storybook-addon-next/tree/main/examples/with-tailwindcss

### Expected behavior

Weback pick up the styles that you import in `preview.js` file.

### How often does this bug happen?

Every time

### Platform

OS: macOS
Node: 0.39.1

### storybook-addon-next version

1.6.6

**Comment by RyanClementsHax** [comment]
Thanks for opening this issue!

Unfortunately I'm not able to reproduce this locally. I checked out the main branch of this repo, and within the `with-tailwindcss` example ran `yarn install`, `yarn build-storybook`, and `npx serve storybook-static`. I was able to see the storybook built and served just fine.

I will unfortunately need a reproduction repo in order to look into this further.

As a side note, I see that you are using node 0.39.1? Is that even a supported node version?
